-- MasterAntiqueRepair schema for Oracle AI Database 26ai (generated from SQL Server catalog 'aspnet-MasterAntiqueRepair-e93a6129-7f74-4486-97e8-8d4ab1a709b4')
-- Run with SQL*Plus. Identifiers are lowercase snake_case, unquoted: Oracle stores them in upper case.
WHENEVER SQLERROR EXIT FAILURE
SET DEFINE OFF

CREATE TABLE roles (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_roles PRIMARY KEY,
    name VARCHAR2(256 CHAR) NOT NULL
);

CREATE TABLE users (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_users PRIMARY KEY,
    name VARCHAR2(256 CHAR) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL,
    password_hash CLOB,
    discriminator VARCHAR2(128 CHAR) NOT NULL,
    deleted_at TIMESTAMP(3),
    email VARCHAR2(256 CHAR),
    email_confirmed BOOLEAN DEFAULT FALSE NOT NULL,
    security_stamp CLOB,
    phone_number CLOB,
    phone_number_confirmed BOOLEAN DEFAULT FALSE NOT NULL,
    two_factor_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    lockout_end_date_utc TIMESTAMP(3),
    lockout_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    access_failed_count NUMBER(10) DEFAULT 0 NOT NULL,
    must_reset_password BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE audit_logs (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_audit_logs PRIMARY KEY,
    timestamp TIMESTAMP(3) NOT NULL,
    user_id NUMBER(10) NOT NULL,
    action NUMBER(10) NOT NULL,
    entity_type NUMBER(10) NOT NULL,
    entity_id NUMBER(10) NOT NULL,
    CONSTRAINT fk_audit_logs_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE tickets (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_tickets PRIMARY KEY,
    state NUMBER(10) NOT NULL,
    description VARCHAR2(2000 CHAR),
    user_id NUMBER(10),
    customer_id NUMBER(10),
    submitted_date TIMESTAMP(3),
    assigned_date TIMESTAMP(3),
    completed_date TIMESTAMP(3),
    CONSTRAINT fk_tickets_users_customer_id FOREIGN KEY (customer_id) REFERENCES users (id),
    CONSTRAINT fk_tickets_users_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE comments (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_comments PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    ticket_id NUMBER(10) NOT NULL,
    text VARCHAR2(2000 CHAR),
    created_at TIMESTAMP(3) NOT NULL,
    CONSTRAINT fk_comments_tickets_ticket_id FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_claims (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_user_claims PRIMARY KEY,
    user_id NUMBER(10) NOT NULL,
    claim_type CLOB,
    claim_value CLOB,
    CONSTRAINT fk_user_claims_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_logins (
    login_provider VARCHAR2(128 CHAR) NOT NULL,
    provider_key VARCHAR2(128 CHAR) NOT NULL,
    user_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_user_logins PRIMARY KEY (login_provider, provider_key, user_id),
    CONSTRAINT fk_user_logins_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
    user_id NUMBER(10) NOT NULL,
    role_id NUMBER(10) NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX ix_comments_ticket_id ON comments (ticket_id);
CREATE INDEX ix_comments_user_id ON comments (user_id);
CREATE UNIQUE INDEX ix_roles_name ON roles (name);
CREATE INDEX ix_tickets_customer_id ON tickets (customer_id);
CREATE INDEX ix_tickets_user_id ON tickets (user_id);
CREATE INDEX ix_user_claims_user_id ON user_claims (user_id);
CREATE INDEX ix_user_logins_user_id ON user_logins (user_id);
CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);
CREATE INDEX ix_user_roles_user_id ON user_roles (user_id);
CREATE UNIQUE INDEX ix_users_name_active ON users (CASE WHEN deleted_at IS NULL THEN LOWER(name) END);
