# Oracle dialect (export only: it renders SQL text and never talks to an Oracle server).
# Dot-sourced by Get-Dialect; helper functions are global: so callers (Export.ps1, Metadata.ps1, SelfTest.ps1) can use them.
# Rules: tools/phase1/dbmigrate/export-oracle/CLAUDE.md ("Names", "Types"). Target: Oracle AI Database 26ai (23ai code line), run through SQL*Plus.
#   - identifiers are lowercase snake_case, unquoted (Oracle folds them to upper case), from an explicit rename map (fails on an
#     unmapped name) and checked against Oracle's reserved words
#   - int identity PK -> NUMBER(10) GENERATED BY DEFAULT AS IDENTITY; bit -> BOOLEAN (23ai and later); datetime -> TIMESTAMP(3);
#     nvarchar(n) -> VARCHAR2(n CHAR); nvarchar(max) -> CLOB
#   - the soft-delete filtered unique index becomes a function-based unique index: CASE WHEN <filter> THEN [LOWER(]col[)] END
#     (Oracle has no partial indexes; a B-tree index does not store all-NULL keys, so filtered-out rows never collide)
#   - ON DELETE NO ACTION is written by leaving the clause out (Oracle does not accept the words)
#   - the SQL files are pure ASCII: control characters are CHR(n), other characters UNISTR('\XXXX'), so nothing depends on the
#     SQL*Plus client character set, line handling or git line-ending conversion
#   - an empty string is refused: Oracle stores '' as NULL, which would silently change the data
#   - data is never lowercased; only identifiers change

$script:OraMaxLineChars = 2000      # SQL*Plus rejects input lines of about 2,499 characters or more; stay well below it
$script:OraLiteralPiece = 1000      # longest run of plain text in one literal piece (a SQL literal is limited to 4000 bytes)
$script:OraJoinLimit = 1500         # a string expression longer than this is split over several lines

# Oracle SQL reserved words (Oracle Database SQL Language Reference, "Oracle SQL Reserved Words"), plus the words SQL*Plus and
# PL/SQL also treat as reserved. Import-oracle cross-checks against V$RESERVED_WORDS on the real database.
$script:OraReservedWords = @('ACCESS','ADD','ALL','ALTER','AND','ANY','ARRAYLEN','AS','ASC','AUDIT','BETWEEN','BY','CHAR','CHECK','CLUSTER','COLUMN','COMMENT','COMPRESS','CONNECT','CREATE','CURRENT','DATE','DECIMAL','DEFAULT','DELETE','DESC','DISTINCT','DROP','ELSE','EXCLUSIVE','EXISTS','FILE','FLOAT','FOR','FROM','GRANT','GROUP','HAVING','IDENTIFIED','IMMEDIATE','IN','INCREMENT','INDEX','INITIAL','INSERT','INTEGER','INTERSECT','INTO','IS','LEVEL','LIKE','LOCK','LONG','MAXEXTENTS','MINUS','MLSLABEL','MODE','MODIFY','NOAUDIT','NOCOMPRESS','NOT','NOTFOUND','NOWAIT','NULL','NUMBER','OF','OFFLINE','ON','ONLINE','OPTION','OR','ORDER','PCTFREE','PRIOR','PRIVILEGES','PUBLIC','RAW','RENAME','RESOURCE','REVOKE','ROW','ROWID','ROWLABEL','ROWNUM','ROWS','SELECT','SESSION','SET','SHARE','SIZE','SMALLINT','SQLBUF','START','SUCCESSFUL','SYNONYM','SYSDATE','TABLE','THEN','TO','TRIGGER','UID','UNION','UNIQUE','UPDATE','USER','VALIDATE','VALUES','VARCHAR','VARCHAR2','VIEW','WHENEVER','WHERE','WITH')

function global:New-OraNameMap {
    $tables = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
    $add = {
        param([string]$Source, [string]$Target, [string[]]$ColumnPairs)
        $cols = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
        for ($i = 0; $i -lt $ColumnPairs.Count; $i += 2) { $cols[$ColumnPairs[$i]] = $ColumnPairs[$i + 1] }
        $tables[$Source] = [pscustomobject]@{ Name = $Target; Columns = $cols }
    }
    & $add 'Roles' 'roles' @('Id', 'id', 'Name', 'name')
    & $add 'Users' 'users' @('Id', 'id', 'Name', 'name', 'CreatedAt', 'created_at', 'PasswordHash', 'password_hash', 'Discriminator', 'discriminator', 'DeletedAt', 'deleted_at', 'Email', 'email', 'EmailConfirmed', 'email_confirmed', 'SecurityStamp', 'security_stamp', 'PhoneNumber', 'phone_number', 'PhoneNumberConfirmed', 'phone_number_confirmed', 'TwoFactorEnabled', 'two_factor_enabled', 'LockoutEndDateUtc', 'lockout_end_date_utc', 'LockoutEnabled', 'lockout_enabled', 'AccessFailedCount', 'access_failed_count', 'MustResetPassword', 'must_reset_password')
    & $add 'AuditLogs' 'audit_logs' @('Id', 'id', 'Timestamp', 'timestamp', 'UserId', 'user_id', 'Action', 'action', 'EntityType', 'entity_type', 'EntityId', 'entity_id')
    & $add 'Tickets' 'tickets' @('Id', 'id', 'State', 'state', 'Description', 'description', 'User_Id', 'user_id', 'Customer_Id', 'customer_id', 'SubmittedDate', 'submitted_date', 'AssignedDate', 'assigned_date', 'CompletedDate', 'completed_date')
    & $add 'Comments' 'comments' @('Id', 'id', 'UserId', 'user_id', 'TicketId', 'ticket_id', 'Text', 'text', 'CreatedAt', 'created_at')
    & $add 'UserClaims' 'user_claims' @('Id', 'id', 'UserId', 'user_id', 'ClaimType', 'claim_type', 'ClaimValue', 'claim_value')
    & $add 'UserLogins' 'user_logins' @('LoginProvider', 'login_provider', 'ProviderKey', 'provider_key', 'UserId', 'user_id')
    & $add 'UserRoles' 'user_roles' @('UserId', 'user_id', 'RoleId', 'role_id')

    # Index names (schema-wide in Oracle). Keys are the model's TargetName (source name, prefixed with the table where the
    # source names collided across tables).
    $indexes = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
    $ix = @('RoleNameIndex', 'ix_roles_name', 'IX_Users_Name_Active', 'ix_users_name_active',
        'AuditLogs_IX_UserId', 'ix_audit_logs_user_id', 'IX_Customer_Id', 'ix_tickets_customer_id', 'IX_User_Id', 'ix_tickets_user_id',
        'Comments_IX_UserId', 'ix_comments_user_id', 'IX_TicketId', 'ix_comments_ticket_id',
        'UserClaims_IX_UserId', 'ix_user_claims_user_id', 'UserLogins_IX_UserId', 'ix_user_logins_user_id',
        'IX_RoleId', 'ix_user_roles_role_id', 'UserRoles_IX_UserId', 'ix_user_roles_user_id')
    for ($i = 0; $i -lt $ix.Count; $i += 2) { $indexes[$ix[$i]] = $ix[$i + 1] }
    return [pscustomobject]@{ Tables = $tables; Indexes = $indexes }
}

function global:Ora-Map { if (-not $global:OraNameMap) { $global:OraNameMap = New-OraNameMap }; return $global:OraNameMap }

function global:Ora-Table([string]$Source) {
    $t = (Ora-Map).Tables[$Source]
    if (-not $t) { throw (New-MigrationError "No Oracle name for table '$Source' - add it to the rename map in dialects\oracle.ps1 (export-oracle\CLAUDE.md, ""Names"")." 2) }
    return $t.Name
}

function global:Ora-Column([string]$Table, [string]$Column) {
    $t = (Ora-Map).Tables[$Table]
    if (-not $t) { throw (New-MigrationError "No Oracle name for table '$Table'." 2) }
    $c = $t.Columns[$Column]
    if (-not $c) { throw (New-MigrationError "No Oracle name for column $Table.$Column - add it to the rename map in dialects\oracle.ps1 (export-oracle\CLAUDE.md, ""Names"")." 2) }
    return $c
}

function global:Ora-IndexName([string]$TargetName) {
    $n = (Ora-Map).Indexes[$TargetName]
    if (-not $n) { throw (New-MigrationError "No Oracle name for index '$TargetName' - add it to the rename map in dialects\oracle.ps1." 2) }
    return $n
}

# fk_<table>_<reftable>_<columns joined by _>, all in target names.
function global:Ora-FkName($Fk) {
    $cols = ($Fk.Columns | ForEach-Object { Ora-Column $Fk.Table $_ }) -join '_'
    return "fk_$(Ora-Table $Fk.Table)_$(Ora-Table $Fk.RefTable)_$cols"
}

# pk_<table>: primary keys are named so the constraint names are the same on every load.
function global:Ora-PkName($Table) { return "pk_$(Ora-Table $Table.Name)" }

# Every identifier this dialect will write, checked against Oracle's rules. Returns the list of problems (empty = fine).
function global:Ora-CheckIdentifiers($Model) {
    $problems = New-Object System.Collections.ArrayList
    $names = New-Object System.Collections.ArrayList
    foreach ($t in $Model.Tables) {
        [void]$names.Add((Ora-Table $t.Name))
        [void]$names.Add((Ora-PkName $t))
        foreach ($c in $t.Columns) { [void]$names.Add((Ora-Column $t.Name $c.Name)) }
        foreach ($fk in $t.ForeignKeys) { [void]$names.Add((Ora-FkName $fk)) }
        foreach ($ix in $t.Indexes) { [void]$names.Add((Ora-IndexName $ix.TargetName)) }
    }
    foreach ($n in ($names | Sort-Object -Unique)) {
        if ($n -cnotmatch '^[a-z][a-z0-9_]*$') { [void]$problems.Add("'$n' is not lowercase letters, digits and underscores") }
        if ($n.Length -gt 128) { [void]$problems.Add("'$n' is longer than 128 bytes") }
        if ($script:OraReservedWords -contains $n.ToUpperInvariant()) { [void]$problems.Add("'$n' is an Oracle reserved word") }
    }
    return , $problems
}

function global:Ora-ColumnType($Col) {
    switch ($Col.Kind) {
        'int' {
            switch ($Col.TypeName) { 'bigint' { return 'NUMBER(19)' } 'smallint' { return 'NUMBER(5)' } 'tinyint' { return 'NUMBER(5)' } default { return 'NUMBER(10)' } }
        }
        'bit' { return 'BOOLEAN' }
        'datetime' { return 'TIMESTAMP(3)' }
        'string' {
            if ($Col.Length -lt 0 -or $Col.TypeName -in 'ntext', 'text') { return 'CLOB' }
            if ($Col.Length -gt 4000) { throw (New-MigrationError "Column $($Col.Name) is a string of length $($Col.Length); VARCHAR2 holds at most 4000 characters - decide between CLOB and a shorter length before exporting." 2) }
            return "VARCHAR2($($Col.Length) CHAR)"
        }
        'binary' { throw (New-MigrationError "Column $($Col.Name) is binary; export-oracle has no mapping for binary columns yet (none in this schema). Add RAW/BLOB rendering and its literal form." 2) }
        'guid' { throw (New-MigrationError "Column $($Col.Name) is a uniqueidentifier; export-oracle has no mapping for it yet (none in this schema). Decide between RAW(16) and VARCHAR2(36)." 2) }
    }
    throw (New-MigrationError "No Oracle type for kind '$($Col.Kind)'." 2)
}

# The type as ALL_TAB_COLUMNS reports it: DATA_TYPE, and the length, precision and scale columns, for the metadata JSON.
function global:Ora-InfoType($Col) {
    switch ($Col.Kind) {
        'int' {
            $p = switch ($Col.TypeName) { 'bigint' { 19 } 'smallint' { 5 } 'tinyint' { 5 } default { 10 } }
            return @{ DataType = 'NUMBER'; MaxLength = $null; Precision = $p; Scale = 0 }
        }
        'bit' { return @{ DataType = 'BOOLEAN'; MaxLength = $null; Precision = $null; Scale = $null } }
        'datetime' { return @{ DataType = 'TIMESTAMP(3)'; MaxLength = $null; Precision = $null; Scale = 3 } }
        'string' {
            if ($Col.Length -lt 0 -or $Col.TypeName -in 'ntext', 'text') { return @{ DataType = 'CLOB'; MaxLength = $null; Precision = $null; Scale = $null } }
            return @{ DataType = 'VARCHAR2'; MaxLength = [int]$Col.Length; Precision = $null; Scale = $null }
        }
    }
    throw (New-MigrationError "No Oracle type for kind '$($Col.Kind)'." 2)
}

function global:Ora-DefaultText($Col) {
    if ($null -eq $Col.Default) { return $null }
    if ($Col.Kind -eq 'bit') {
        if ($Col.Default -eq '0') { return 'FALSE' }
        if ($Col.Default -eq '1') { return 'TRUE' }
        throw (New-MigrationError "Unsupported bit default '$($Col.Default)' on $($Col.Name)." 2)
    }
    if ($Col.Kind -in 'datetime', 'binary', 'guid') { throw (New-MigrationError "Unsupported default on $($Col.Kind) column $($Col.Name)." 2) }
    return $Col.Default
}

# Translates a SQL Server filtered-index predicate. Only [col] IS [NOT] NULL (AND-ed) is understood; anything else is an
# error so a business rule is never silently dropped. The result is a condition in Oracle names.
function global:Ora-TranslateFilter([string]$Table, [string]$Filter) {
    $parts = New-Object System.Collections.ArrayList
    foreach ($p in ($Filter.Trim() -split '\s+AND\s+', 0, 'IgnoreCase')) {
        $q = $p.Trim()
        while ($q.StartsWith('(') -and $q.EndsWith(')')) { $q = $q.Substring(1, $q.Length - 2).Trim() }
        if ($q -notmatch '^\[(\w+)\]\s+IS\s+(NOT\s+)?NULL$') {
            throw (New-MigrationError "Cannot translate index filter '$Filter' to Oracle - extend Ora-TranslateFilter." 2)
        }
        $neg = if ($Matches[2]) { 'NOT ' } else { '' }
        [void]$parts.Add("$(Ora-Column $Table $Matches[1]) IS ${neg}NULL")
    }
    return ($parts -join ' AND ')
}

# Set of 'Table|Column' pairs whose unique index compares case-insensitively (LOWER(col)); from the target's config.
function global:Ora-CaseInsensitiveSet($Settings) {
    $set = @{}
    if ($Settings -and $Settings.caseInsensitiveUniqueIndexes) {
        foreach ($e in $Settings.caseInsensitiveUniqueIndexes) { $set["$($e.table)|$($e.column)"] = $true }
    }
    return $set
}

# The key expression of one index column, or $null when the plain column is indexed. Used by the schema file and the metadata.
#   case-insensitive unique column   -> LOWER(col)
#   filtered index                   -> CASE WHEN <filter> THEN <col or LOWER(col)> END   (Oracle has no partial index)
function global:Ora-IndexColumnExpression($Ix, $IxCol, $Ci) {
    $cn = Ora-Column $Ix.Table $IxCol.Name
    $expr = $cn
    if ($Ix.Unique -and $Ci.ContainsKey("$($Ix.Table)|$($IxCol.Name)")) { $expr = "LOWER($cn)" }
    if ($Ix.Filter) { $expr = "CASE WHEN $(Ora-TranslateFilter $Ix.Table $Ix.Filter) THEN $expr END" }
    if ($expr -ceq $cn) { return $null }
    return $expr
}

function global:Ora-FkDeleteClause([string]$OnDelete, [string]$Name) {
    switch ($OnDelete.Replace('_', ' ').ToUpperInvariant()) {
        'CASCADE' { return ' ON DELETE CASCADE' }
        'NO ACTION' { return '' }
        'SET NULL' { return ' ON DELETE SET NULL' }
    }
    throw (New-MigrationError "Foreign key $Name has delete action '$OnDelete', which Oracle cannot express." 2)
}

function global:Ora-RenderSchema($Model, [string]$SourceName, $Settings) {
    $problems = Ora-CheckIdentifiers $Model
    if ($problems.Count -gt 0) { throw (New-MigrationError ("Oracle identifier problem(s): " + ($problems -join '; ') + " - change the rename map in dialects\oracle.ps1.") 2) }
    $ci = Ora-CaseInsensitiveSet $Settings
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("-- MasterAntiqueRepair schema for Oracle AI Database 26ai (generated from SQL Server catalog '$SourceName')`n")
    [void]$sb.Append("-- Run with SQL*Plus. Identifiers are lowercase snake_case, unquoted: Oracle stores them in upper case.`n")
    [void]$sb.Append("WHENEVER SQLERROR EXIT FAILURE`nSET DEFINE OFF`n`n")
    foreach ($t in $Model.Tables) {
        $tn = Ora-Table $t.Name
        $defs = New-Object System.Collections.ArrayList
        foreach ($c in $t.Columns) {
            $cn = Ora-Column $t.Name $c.Name
            $d = "$cn $(Ora-ColumnType $c)"
            if ($c.IsIdentity) {
                if ($t.PrimaryKey.Count -ne 1 -or $t.PrimaryKey[0] -ne $c.Name -or $c.Kind -ne 'int') {
                    throw (New-MigrationError "Identity column $($t.Name).$($c.Name) is not a single-column integer primary key - not supported." 2)
                }
                $d += " GENERATED BY DEFAULT AS IDENTITY CONSTRAINT $(Ora-PkName $t) PRIMARY KEY"
            } else {
                # Oracle wants DEFAULT before NOT NULL.
                $def = Ora-DefaultText $c
                if ($null -ne $def) { $d += " DEFAULT $def" }
                if (-not $c.Nullable) { $d += ' NOT NULL' }
            }
            [void]$defs.Add($d)
        }
        if (-not $t.Identity -and $t.PrimaryKey.Count -gt 0) {
            [void]$defs.Add("CONSTRAINT $(Ora-PkName $t) PRIMARY KEY ($(($t.PrimaryKey | ForEach-Object { Ora-Column $t.Name $_ }) -join ', '))")
        }
        foreach ($fk in ($t.ForeignKeys | Sort-Object { Ora-FkName $_ })) {
            $cols = ($fk.Columns | ForEach-Object { Ora-Column $fk.Table $_ }) -join ', '
            $refs = ($fk.RefColumns | ForEach-Object { Ora-Column $fk.RefTable $_ }) -join ', '
            [void]$defs.Add("CONSTRAINT $(Ora-FkName $fk) FOREIGN KEY ($cols) REFERENCES $(Ora-Table $fk.RefTable) ($refs)$(Ora-FkDeleteClause ([string]$fk.OnDelete) $fk.Name)")
        }
        [void]$sb.Append("CREATE TABLE $tn (`n    $($defs -join ",`n    ")`n);`n`n")
    }
    $indexes = New-Object System.Collections.ArrayList
    foreach ($t in $Model.Tables) { foreach ($ix in $t.Indexes) { [void]$indexes.Add($ix) } }
    foreach ($ix in ($indexes | Sort-Object { Ora-IndexName $_.TargetName })) {
        $u = if ($ix.Unique) { 'UNIQUE ' } else { '' }
        $cols = ($ix.Columns | ForEach-Object {
            $e = Ora-IndexColumnExpression $ix $_ $ci
            $k = if ($e) { $e } else { Ora-Column $ix.Table $_.Name }
            if ($_.Descending) { "$k DESC" } else { $k }
        }) -join ', '
        [void]$sb.Append("CREATE ${u}INDEX $(Ora-IndexName $ix.TargetName) ON $(Ora-Table $ix.Table) ($cols);`n")
    }
    return $sb.ToString()
}

# One string value as a SQL expression made only of ASCII: plain runs 'text', control characters CHR(n), any other character
# UNISTR('\XXXX') (UTF-16 code units). Pieces are joined with || and spread over lines when long. A CLOB column starts with TO_CLOB.
function global:Ora-StringExpr([string]$S, [bool]$Clob, [string]$ColName) {
    if ($S.Length -eq 0) { throw (New-MigrationError "Column $ColName holds an empty string; Oracle stores '' as NULL, which would change the data. Decide how the data owner wants empty text migrated before exporting." 2) }
    if ($S.IndexOf([char]0) -ge 0) { throw (New-MigrationError "A string value contains NUL, which Oracle text cannot store (column $ColName)." 2) }
    $pieces = New-Object System.Collections.ArrayList
    $run = New-Object System.Text.StringBuilder
    $uni = New-Object System.Text.StringBuilder
    $flushRun = { if ($run.Length -gt 0) { [void]$pieces.Add("'" + $run.ToString().Replace("'", "''") + "'"); [void]$run.Clear() } }
    $flushUni = { if ($uni.Length -gt 0) { [void]$pieces.Add("UNISTR('" + $uni.ToString() + "')"); [void]$uni.Clear() } }
    foreach ($ch in $S.ToCharArray()) {
        $code = [int]$ch
        if ($code -ge 32 -and $code -le 126) {
            & $flushUni
            [void]$run.Append($ch)
            if ($run.Length -ge $script:OraLiteralPiece) { & $flushRun }
        } elseif ($code -lt 32 -or $code -eq 127) {
            & $flushRun; & $flushUni
            [void]$pieces.Add("CHR($code)")
        } else {
            & $flushRun
            [void]$uni.Append(('\{0:X4}' -f $code))
            if ($uni.Length -ge 200) { & $flushUni }
        }
    }
    & $flushRun; & $flushUni
    if ($Clob) { $pieces[0] = "TO_CLOB(" + $pieces[0] + ")" }
    $total = 4 * ($pieces.Count - 1)
    foreach ($p in $pieces) { $total += $p.Length }
    if ($total -le $script:OraJoinLimit) { return ($pieces -join ' || ') }
    return ($pieces -join " ||`n    ")
}

# Renders one canonical value as an Oracle literal.
function global:Ora-Literal($Canonical, $Col) {
    if ($null -eq $Canonical) { return 'NULL' }
    switch ($Col.Kind) {
        'int' { return $Canonical }
        'bit' { if ($Canonical -eq '1') { return 'TRUE' } else { return 'FALSE' } }
        'datetime' { return "TIMESTAMP '" + (ConvertTo-Ts3 $Canonical) + "'" }
        'binary' { throw (New-MigrationError "Column $($Col.Name) is binary; not supported by export-oracle yet." 2) }
        'guid' { throw (New-MigrationError "Column $($Col.Name) is a uniqueidentifier; not supported by export-oracle yet." 2) }
        default {
            $clob = ($Col.Length -lt 0 -or $Col.TypeName -in 'ntext', 'text')
            return (Ora-StringExpr ([string]$Canonical) $clob $Col.Name)
        }
    }
}

# One row as text: cells joined by ', ' in parentheses; a cell that would push a line past the limit starts a new line.
function global:Ora-RenderRow($Cells) {
    $lines = New-Object System.Collections.ArrayList
    $cur = '('
    for ($i = 0; $i -lt $Cells.Count; $i++) {
        $parts = ([string]$Cells[$i]) -split "`n"
        $sep = if ($i -eq 0) { '' } else { ', ' }
        if ($i -gt 0 -and ($cur.Length + $sep.Length + $parts[0].Length) -gt 1800) {
            [void]$lines.Add($cur + ',')
            $cur = '    ' + $parts[0]
        } else { $cur += $sep + $parts[0] }
        for ($p = 1; $p -lt $parts.Count; $p++) { [void]$lines.Add($cur); $cur = $parts[$p] }
    }
    [void]$lines.Add($cur + ')')
    return ($lines -join "`n")
}

function global:Ora-RenderData($Model, $RowsByTable) {
    $batch = 100
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("-- MasterAntiqueRepair data for Oracle AI Database 26ai (credentials sanitized). Run with SQL*Plus.`n")
    [void]$sb.Append("WHENEVER SQLERROR EXIT FAILURE ROLLBACK`nSET DEFINE OFF`n`n")
    foreach ($t in $Model.Tables) {
        $tn = Ora-Table $t.Name
        $rows = $RowsByTable[$t.Name]
        if ($rows.Count -gt 0) {
            $colList = ($t.Columns | ForEach-Object { Ora-Column $t.Name $_.Name }) -join ', '
            for ($start = 0; $start -lt $rows.Count; $start += $batch) {
                $end = [Math]::Min($start + $batch, $rows.Count)
                $lines = for ($r = $start; $r -lt $end; $r++) {
                    $cells = for ($i = 0; $i -lt $t.Columns.Count; $i++) { Ora-Literal $rows[$r][$i] $t.Columns[$i] }
                    Ora-RenderRow @($cells)
                }
                [void]$sb.Append("INSERT INTO $tn ($colList) VALUES`n$($lines -join ",`n");`n")
            }
        }
    }
    [void]$sb.Append("`nCOMMIT;`n`n")
    # The identity columns continue after the last value the source ever issued (ALTER commits by itself, so it follows the data).
    foreach ($t in $Model.Tables) {
        if ($t.Identity -and $null -ne $t.IdentityLast) {
            [void]$sb.Append("ALTER TABLE $(Ora-Table $t.Name) MODIFY ($(Ora-Column $t.Name $t.Identity) GENERATED BY DEFAULT AS IDENTITY (RESTART START WITH $([int64]$t.IdentityLast + 1)));`n")
        }
    }
    return $sb.ToString()
}

function global:Ora-KnownDifferences {
    return @(
        'Identifiers are lowercase snake_case in the SQL (for example CreatedAt becomes created_at; User_Id becomes user_id) and Oracle stores them in upper case; foreign key and index names are renamed too. Data values are never lowercased.',
        'datetime columns become TIMESTAMP(3) without time zone and keep the source values exactly; it is not known whether the legacy application stored UTC or local times (only LockoutEndDateUtc is UTC by name), so no zone conversion is made.',
        'SQL Server compared text case-insensitively; Oracle is case-sensitive. Username uniqueness is enforced case-insensitively by a function-based unique index on CASE WHEN deleted_at IS NULL THEN LOWER(name) END (Oracle has no partial index), so authentication must compare LOWER(name) = LOWER(input). Role names use a plain case-sensitive unique index.',
        'bit columns become the native BOOLEAN type (Oracle 23ai and later; not available on 19c); the identity columns become GENERATED BY DEFAULT AS IDENTITY and the data supplies explicit ids (each identity is restarted after the last issued value once the data is loaded).',
        'Oracle stores an empty string as NULL. The export refuses a source that contains an empty string (there is none), because loading it would silently turn it into NULL.',
        'ON DELETE NO ACTION is written by leaving the clause out: Oracle rejects the words, and its default already means no action.',
        'nvarchar(n) becomes VARCHAR2(n CHAR): the length is in characters, but a VARCHAR2 value is also limited to 4000 bytes unless the database has MAX_STRING_SIZE=EXTENDED, so multi-byte text near the limit can overflow.',
        'The SQL files are pure ASCII: control characters are written as CHR(n) and non-ASCII characters as UNISTR(''\XXXX''), so loading does not depend on the client character set.',
        'Index names that were duplicated across tables in SQL Server (for example IX_UserId) were prefixed with the table name, then renamed to snake_case.'
    )
}

function New-Dialect($Settings) {
    return @{
        Name             = 'oracle'
        DisplayName      = 'Oracle AI Database 26ai'
        KnownDifferences = (Ora-KnownDifferences)
        RenderSchema     = { param($m, $s, $st) Ora-RenderSchema $m $s $st }
        RenderData       = { param($m, $r) Ora-RenderData $m $r }
    }
}
