-- MasterAntiqueRepair schema for PostgreSQL 15+ (generated from SQL Server catalog 'aspnet-MasterAntiqueRepair-e93a6129-7f74-4486-97e8-8d4ab1a709b4')
-- Identifiers are lowercase snake_case; nothing here needs quoting.
BEGIN;

CREATE TABLE roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    password_hash TEXT,
    discriminator VARCHAR(128) NOT NULL,
    deleted_at TIMESTAMP,
    email VARCHAR(256),
    email_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    security_stamp TEXT,
    phone_number TEXT,
    phone_number_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    lockout_end_date_utc TIMESTAMP,
    lockout_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    access_failed_count INTEGER NOT NULL DEFAULT 0,
    must_reset_password BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    user_id INTEGER NOT NULL,
    action INTEGER NOT NULL,
    entity_type INTEGER NOT NULL,
    entity_id INTEGER NOT NULL,
    CONSTRAINT fk_audit_logs_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state INTEGER NOT NULL,
    description VARCHAR(2000),
    user_id INTEGER,
    customer_id INTEGER,
    submitted_date TIMESTAMP,
    assigned_date TIMESTAMP,
    completed_date TIMESTAMP,
    CONSTRAINT fk_tickets_users_customer_id FOREIGN KEY (customer_id) REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT fk_tickets_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE comments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    ticket_id INTEGER NOT NULL,
    text VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_tickets_ticket_id FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    claim_type TEXT,
    claim_value TEXT,
    CONSTRAINT fk_user_claims_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_logins (
    login_provider VARCHAR(128) NOT NULL,
    provider_key VARCHAR(128) NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (login_provider, provider_key, user_id),
    CONSTRAINT fk_user_logins_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_roles (
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);
CREATE INDEX ix_comments_ticket_id ON comments (ticket_id);
CREATE INDEX ix_comments_user_id ON comments (user_id);
CREATE UNIQUE INDEX ix_roles_name ON roles (name);
CREATE INDEX ix_tickets_customer_id ON tickets (customer_id);
CREATE INDEX ix_tickets_user_id ON tickets (user_id);
CREATE INDEX ix_user_claims_user_id ON user_claims (user_id);
CREATE INDEX ix_user_logins_user_id ON user_logins (user_id);
CREATE INDEX ix_user_roles_role_id ON user_roles (role_id);
CREATE INDEX ix_user_roles_user_id ON user_roles (user_id);
CREATE UNIQUE INDEX ix_users_name_active ON users (lower(name)) WHERE deleted_at IS NULL;

COMMIT;
