# PostgreSQL dialect (export only: it renders SQL text and never talks to a PostgreSQL server).
# Dot-sourced by Get-Dialect; helper functions are global: so callers (Export.ps1, Metadata.ps1) can use them.
# Rules: tools/phase1/dbmigrate/export-postgresql/CLAUDE.md ("Names", "Types"). Target: PostgreSQL 15 or later.
#   - identifiers are lowercase snake_case, unquoted, from an explicit rename map (fails on an unmapped name)
#   - INTEGER identity PK -> INTEGER GENERATED BY DEFAULT AS IDENTITY; bit -> BOOLEAN; datetime -> TIMESTAMP (no time zone,
#     literals with 3 fractional digits); nvarchar(n) -> VARCHAR(n); nvarchar(max) -> TEXT
#   - the soft-delete filtered unique index becomes a partial unique index on lower(name) (case-insensitive usernames, decision 2)
#   - data is never lowercased; only identifiers change

function global:New-PgNameMap {
    $tables = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
    $add = {
        param([string]$Source, [string]$Target, [string[]]$ColumnPairs)
        $cols = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
        for ($i = 0; $i -lt $ColumnPairs.Count; $i += 2) { $cols[$ColumnPairs[$i]] = $ColumnPairs[$i + 1] }
        $tables[$Source] = [pscustomobject]@{ Name = $Target; Columns = $cols }
    }
    & $add 'Roles' 'roles' @('Id', 'id', 'Name', 'name')
    & $add 'Users' 'users' @('Id', 'id', 'Name', 'name', 'CreatedAt', 'created_at', 'PasswordHash', 'password_hash', 'Discriminator', 'discriminator', 'DeletedAt', 'deleted_at', 'Email', 'email', 'EmailConfirmed', 'email_confirmed', 'SecurityStamp', 'security_stamp', 'PhoneNumber', 'phone_number', 'PhoneNumberConfirmed', 'phone_number_confirmed', 'TwoFactorEnabled', 'two_factor_enabled', 'LockoutEndDateUtc', 'lockout_end_date_utc', 'LockoutEnabled', 'lockout_enabled', 'AccessFailedCount', 'access_failed_count', 'MustResetPassword', 'must_reset_password')
    & $add 'AuditLogs' 'audit_logs' @('Id', 'id', 'Timestamp', 'timestamp', 'UserId', 'user_id', 'Action', 'action', 'EntityType', 'entity_type', 'EntityId', 'entity_id')
    & $add 'Tickets' 'tickets' @('Id', 'id', 'State', 'state', 'Description', 'description', 'User_Id', 'user_id', 'Customer_Id', 'customer_id', 'SubmittedDate', 'submitted_date', 'AssignedDate', 'assigned_date', 'CompletedDate', 'completed_date')
    & $add 'Comments' 'comments' @('Id', 'id', 'UserId', 'user_id', 'TicketId', 'ticket_id', 'Text', 'text', 'CreatedAt', 'created_at')
    & $add 'UserClaims' 'user_claims' @('Id', 'id', 'UserId', 'user_id', 'ClaimType', 'claim_type', 'ClaimValue', 'claim_value')
    & $add 'UserLogins' 'user_logins' @('LoginProvider', 'login_provider', 'ProviderKey', 'provider_key', 'UserId', 'user_id')
    & $add 'UserRoles' 'user_roles' @('UserId', 'user_id', 'RoleId', 'role_id')

    # Index names (schema-wide in PostgreSQL). Keys are the model's TargetName (source name, prefixed with the table where
    # the source names collided across tables).
    $indexes = New-Object System.Collections.Hashtable ([StringComparer]::Ordinal)
    $ix = @('RoleNameIndex', 'ix_roles_name', 'IX_Users_Name_Active', 'ix_users_name_active',
        'AuditLogs_IX_UserId', 'ix_audit_logs_user_id', 'IX_Customer_Id', 'ix_tickets_customer_id', 'IX_User_Id', 'ix_tickets_user_id',
        'Comments_IX_UserId', 'ix_comments_user_id', 'IX_TicketId', 'ix_comments_ticket_id',
        'UserClaims_IX_UserId', 'ix_user_claims_user_id', 'UserLogins_IX_UserId', 'ix_user_logins_user_id',
        'IX_RoleId', 'ix_user_roles_role_id', 'UserRoles_IX_UserId', 'ix_user_roles_user_id')
    for ($i = 0; $i -lt $ix.Count; $i += 2) { $indexes[$ix[$i]] = $ix[$i + 1] }
    return [pscustomobject]@{ Tables = $tables; Indexes = $indexes }
}

function global:Pg-Map { if (-not $global:PgNameMap) { $global:PgNameMap = New-PgNameMap }; return $global:PgNameMap }

function global:Pg-Table([string]$Source) {
    $t = (Pg-Map).Tables[$Source]
    if (-not $t) { throw (New-MigrationError "No PostgreSQL name for table '$Source' - add it to the rename map in dialects\postgres.ps1 (export-postgresql\CLAUDE.md, "Names")." 2) }
    return $t.Name
}

function global:Pg-Column([string]$Table, [string]$Column) {
    $t = (Pg-Map).Tables[$Table]
    if (-not $t) { throw (New-MigrationError "No PostgreSQL name for table '$Table'." 2) }
    $c = $t.Columns[$Column]
    if (-not $c) { throw (New-MigrationError "No PostgreSQL name for column $Table.$Column - add it to the rename map in dialects\postgres.ps1 (export-postgresql\CLAUDE.md, "Names")." 2) }
    return $c
}

function global:Pg-IndexName([string]$TargetName) {
    $n = (Pg-Map).Indexes[$TargetName]
    if (-not $n) { throw (New-MigrationError "No PostgreSQL name for index '$TargetName' - add it to the rename map in dialects\postgres.ps1." 2) }
    return $n
}

# fk_<table>_<reftable>_<columns joined by _>, all in target names.
function global:Pg-FkName($Fk) {
    $cols = ($Fk.Columns | ForEach-Object { Pg-Column $Fk.Table $_ }) -join '_'
    return "fk_$(Pg-Table $Fk.Table)_$(Pg-Table $Fk.RefTable)_$cols"
}

function global:Pg-ColumnType($Col) {
    switch ($Col.Kind) {
        'int' {
            switch ($Col.TypeName) { 'bigint' { return 'BIGINT' } 'smallint' { return 'SMALLINT' } 'tinyint' { return 'SMALLINT' } default { return 'INTEGER' } }
        }
        'bit' { return 'BOOLEAN' }
        'datetime' { return 'TIMESTAMP' }
        'binary' { return 'BYTEA' }
        'guid' { return 'UUID' }
        'string' {
            if ($Col.Length -lt 0 -or $Col.TypeName -in 'ntext', 'text') { return 'TEXT' }
            return "VARCHAR($($Col.Length))"
        }
    }
    throw (New-MigrationError "No PostgreSQL type for kind '$($Col.Kind)'." 2)
}

# The type as information_schema.columns reports it (data_type) plus character_maximum_length, for the metadata JSON.
function global:Pg-InfoType($Col) {
    switch ($Col.Kind) {
        'int' { $t = switch ($Col.TypeName) { 'bigint' { 'bigint' } 'smallint' { 'smallint' } 'tinyint' { 'smallint' } default { 'integer' } }; return @{ DataType = $t; MaxLength = $null } }
        'bit' { return @{ DataType = 'boolean'; MaxLength = $null } }
        'datetime' { return @{ DataType = 'timestamp without time zone'; MaxLength = $null } }
        'binary' { return @{ DataType = 'bytea'; MaxLength = $null } }
        'guid' { return @{ DataType = 'uuid'; MaxLength = $null } }
        'string' {
            if ($Col.Length -lt 0 -or $Col.TypeName -in 'ntext', 'text') { return @{ DataType = 'text'; MaxLength = $null } }
            return @{ DataType = 'character varying'; MaxLength = [int]$Col.Length }
        }
    }
    throw (New-MigrationError "No PostgreSQL type for kind '$($Col.Kind)'." 2)
}

function global:Pg-DefaultText($Col) {
    if ($null -eq $Col.Default) { return $null }
    if ($Col.Kind -eq 'bit') {
        if ($Col.Default -eq '0') { return 'FALSE' }
        if ($Col.Default -eq '1') { return 'TRUE' }
        throw (New-MigrationError "Unsupported bit default '$($Col.Default)' on $($Col.Name)." 2)
    }
    if ($Col.Kind -in 'datetime', 'binary', 'guid') { throw (New-MigrationError "Unsupported default on $($Col.Kind) column $($Col.Name)." 2) }
    return $Col.Default
}

# Translates a SQL Server filtered-index predicate. Only [col] IS [NOT] NULL (AND-ed) is understood; anything else is an
# error so a business rule is never silently dropped.
function global:Pg-TranslateFilter([string]$Table, [string]$Filter) {
    $parts = New-Object System.Collections.ArrayList
    foreach ($p in ($Filter.Trim() -split '\s+AND\s+', 0, 'IgnoreCase')) {
        $q = $p.Trim()
        while ($q.StartsWith('(') -and $q.EndsWith(')')) { $q = $q.Substring(1, $q.Length - 2).Trim() }
        if ($q -notmatch '^\[(\w+)\]\s+IS\s+(NOT\s+)?NULL$') {
            throw (New-MigrationError "Cannot translate index filter '$Filter' to PostgreSQL - extend Pg-TranslateFilter." 2)
        }
        $neg = if ($Matches[2]) { 'NOT ' } else { '' }
        [void]$parts.Add("$(Pg-Column $Table $Matches[1]) IS ${neg}NULL")
    }
    return ($parts -join ' AND ')
}

# Set of 'Table|Column' pairs whose unique index compares case-insensitively (lower(col)); from the target's config.
function global:Pg-CaseInsensitiveSet($Settings) {
    $set = @{}
    if ($Settings -and $Settings.caseInsensitiveUniqueIndexes) {
        foreach ($e in $Settings.caseInsensitiveUniqueIndexes) { $set["$($e.table)|$($e.column)"] = $true }
    }
    return $set
}

function global:Pg-RenderSchema($Model, [string]$SourceName, $Settings) {
    $ci = Pg-CaseInsensitiveSet $Settings
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("-- MasterAntiqueRepair schema for PostgreSQL 15+ (generated from SQL Server catalog '$SourceName')`n")
    [void]$sb.Append("-- Identifiers are lowercase snake_case; nothing here needs quoting.`n")
    [void]$sb.Append("BEGIN;`n`n")
    foreach ($t in $Model.Tables) {
        $tn = Pg-Table $t.Name
        $defs = New-Object System.Collections.ArrayList
        foreach ($c in $t.Columns) {
            $cn = Pg-Column $t.Name $c.Name
            $d = "$cn $(Pg-ColumnType $c)"
            if ($c.IsIdentity) {
                if ($t.PrimaryKey.Count -ne 1 -or $t.PrimaryKey[0] -ne $c.Name -or $c.Kind -ne 'int') {
                    throw (New-MigrationError "Identity column $($t.Name).$($c.Name) is not a single-column integer primary key - not supported." 2)
                }
                $d += ' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
            } else {
                if (-not $c.Nullable) { $d += ' NOT NULL' }
                $def = Pg-DefaultText $c
                if ($null -ne $def) { $d += " DEFAULT $def" }
            }
            [void]$defs.Add($d)
        }
        if (-not $t.Identity -and $t.PrimaryKey.Count -gt 0) {
            [void]$defs.Add("PRIMARY KEY ($(($t.PrimaryKey | ForEach-Object { Pg-Column $t.Name $_ }) -join ', '))")
        }
        foreach ($fk in ($t.ForeignKeys | Sort-Object { Pg-FkName $_ })) {
            $cols = ($fk.Columns | ForEach-Object { Pg-Column $fk.Table $_ }) -join ', '
            $refs = ($fk.RefColumns | ForEach-Object { Pg-Column $fk.RefTable $_ }) -join ', '
            [void]$defs.Add("CONSTRAINT $(Pg-FkName $fk) FOREIGN KEY ($cols) REFERENCES $(Pg-Table $fk.RefTable) ($refs) ON DELETE $($fk.OnDelete)")
        }
        [void]$sb.Append("CREATE TABLE $tn (`n    $($defs -join ",`n    ")`n);`n`n")
    }
    $indexes = New-Object System.Collections.ArrayList
    foreach ($t in $Model.Tables) { foreach ($ix in $t.Indexes) { [void]$indexes.Add($ix) } }
    foreach ($ix in ($indexes | Sort-Object { Pg-IndexName $_.TargetName })) {
        $u = if ($ix.Unique) { 'UNIQUE ' } else { '' }
        $cols = ($ix.Columns | ForEach-Object {
            $cn = Pg-Column $ix.Table $_.Name
            if ($ix.Unique -and $ci.ContainsKey("$($ix.Table)|$($_.Name)")) { $cn = "lower($cn)" }
            if ($_.Descending) { "$cn DESC" } else { $cn }
        }) -join ', '
        $w = if ($ix.Filter) { " WHERE $(Pg-TranslateFilter $ix.Table $ix.Filter)" } else { '' }
        [void]$sb.Append("CREATE ${u}INDEX $(Pg-IndexName $ix.TargetName) ON $(Pg-Table $ix.Table) ($cols)$w;`n")
    }
    [void]$sb.Append("`nCOMMIT;`n")
    return $sb.ToString()
}

# Renders one canonical value as a PostgreSQL literal.
function global:Pg-Literal($Canonical, $Col) {
    if ($null -eq $Canonical) { return 'NULL' }
    switch ($Col.Kind) {
        'int' { return $Canonical }
        'bit' { if ($Canonical -eq '1') { return 'true' } else { return 'false' } }
        'datetime' { return "'" + (ConvertTo-Ts3 $Canonical) + "'" }
        'binary' { return "'\x" + $Canonical.ToLowerInvariant() + "'" }
        'guid' { return "'" + $Canonical + "'" }
        default {
            if ($Canonical.IndexOf([char]0) -ge 0) { throw (New-MigrationError "A string value contains NUL, which PostgreSQL text cannot store (column $($Col.Name))." 2) }
            # CR and every other control character except TAB and LF are emitted as chr(n) so git line-ending conversion or an
            # editor can never alter data; TAB and LF stay raw (readable).
            if ($Canonical -notmatch '[\x00-\x08\x0B-\x1F\x7F]') { return "'" + $Canonical.Replace("'", "''") + "'" }
            $parts = New-Object System.Collections.ArrayList
            $run = New-Object System.Text.StringBuilder
            foreach ($ch in $Canonical.ToCharArray()) {
                $code = [int]$ch
                if (($code -le 8) -or ($code -ge 11 -and $code -le 31) -or $code -eq 127) {
                    if ($run.Length -gt 0) { [void]$parts.Add("'" + $run.ToString().Replace("'", "''") + "'"); [void]$run.Clear() }
                    [void]$parts.Add("chr($code)")
                } else { [void]$run.Append($ch) }
            }
            if ($run.Length -gt 0) { [void]$parts.Add("'" + $run.ToString().Replace("'", "''") + "'") }
            return '(' + ($parts -join ' || ') + ')'
        }
    }
}

function global:Pg-RenderData($Model, $RowsByTable) {
    $batch = 100
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("-- MasterAntiqueRepair data for PostgreSQL 15+ (credentials sanitized)`n")
    [void]$sb.Append("SET client_encoding = 'UTF8';`nSET standard_conforming_strings = on;`nBEGIN;`n")
    foreach ($t in $Model.Tables) {
        $tn = Pg-Table $t.Name
        $rows = $RowsByTable[$t.Name]
        if ($rows.Count -gt 0) {
            $colList = ($t.Columns | ForEach-Object { Pg-Column $t.Name $_.Name }) -join ', '
            for ($start = 0; $start -lt $rows.Count; $start += $batch) {
                $end = [Math]::Min($start + $batch, $rows.Count)
                $lines = for ($r = $start; $r -lt $end; $r++) {
                    $vals = for ($i = 0; $i -lt $t.Columns.Count; $i++) { Pg-Literal $rows[$r][$i] $t.Columns[$i] }
                    "(" + ($vals -join ', ') + ")"
                }
                [void]$sb.Append("INSERT INTO $tn ($colList) VALUES`n$($lines -join ",`n");`n")
            }
        }
        if ($t.Identity -and $null -ne $t.IdentityLast) {
            [void]$sb.Append("SELECT setval(pg_get_serial_sequence('$tn', '$(Pg-Column $t.Name $t.Identity)'), $($t.IdentityLast));`n")
        }
    }
    [void]$sb.Append("COMMIT;`n")
    return $sb.ToString()
}

function global:Pg-KnownDifferences {
    return @(
        'Identifiers are lowercase snake_case (for example CreatedAt becomes created_at; User_Id becomes user_id); foreign key and index names are renamed too. Data values are never lowercased.',
        'datetime columns become TIMESTAMP without time zone and keep the source values exactly; it is not known whether the legacy application stored UTC or local times (only LockoutEndDateUtc is UTC by name), so no zone conversion is made.',
        'SQL Server compared text case-insensitively; PostgreSQL is case-sensitive. Username uniqueness is enforced case-insensitively by a partial unique index on lower(name) where deleted_at IS NULL, so authentication must compare lower(name) = lower(input). Role names use a plain case-sensitive unique index.',
        'bit columns become BOOLEAN; the identity columns become GENERATED BY DEFAULT AS IDENTITY and the data supplies explicit ids (the sequences are reset after the load).',
        'Index names that were duplicated across tables in SQL Server (for example IX_UserId) were prefixed with the table name, then renamed to snake_case.'
    )
}

function New-Dialect($Settings) {
    return @{
        Name             = 'postgres'
        DisplayName      = 'PostgreSQL 15+'
        KnownDifferences = (Pg-KnownDifferences)
        RenderSchema     = { param($m, $s, $st) Pg-RenderSchema $m $s $st }
        RenderData       = { param($m, $r) Pg-RenderData $m $r }
    }
}
